[workspace]
members = ["crates/*"]
default-members = ["crates/core"]
resolver = "2"

[workspace.dependencies]
alith-core = { path = "crates/core" }
llm_client = { git = "https://github.com/lazai-labs/llm_client", version = "0.1.0" }
llm_models = { git = "https://github.com/lazai-labs/llm_client", version = "0.1.0" }

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.83"
exclude = [".github/"]
