[package]
name = "alith-inference"
description = "Alith inference package"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
alith-core.workspace = true

thiserror.workspace = true
ort = { version = "=2.0.0-rc.9", default-features = false, features = [
  "ndarray",
  "cuda",
  "tensorrt",
  "fetch-models",
] }
tokenizers = "0.21.1"

[features]
inference = []
